### ISSUE TITLE
Returning -10000000

### ISSUE THREAD

**Issue by please-help** [EngineerTony/Sensirion_SDP6x_pressure_sens#2]
Hi,
Firstly I would like to thank you for providing this library. 

I was wondering if someone could please help me. I am using a Sensirion SDP610 25Pa differential pressure sensor. I am using the code here but keep getting a return value of -10000000. Does anyone have any suggestions on how I can fix this error?

Thanks!

**Comment by EngineerTony** [comment]
Hi,
Thanks for the question.
The Arduino returns -1000000 when it failed to read from the sensor.
Could you check your connections please? There is a connection diagram on the Readme page, make sure the SDP610 is connected to 3.3v and ground and that the SDA and SCL connections are connected to 3.3V (through pull up resistors each somewhere between 2.5k and 10kohm) and pins A4 and A5 on the Uno. (The pins may be different for a different type of Arduino).
Thanks
